import { NzConfig } from 'ng-zorro-antd/core/config';
import { IconDefinition } from '@ant-design/icons-angular';
import {
  //fill
  StarFill,
  StopFill,
  TrademarkCircleFill,
  FlagFill,
  // outline
  LogoutOutline,
  UserOutline,
  EditOutline,
  DownloadOutline,
  FolderOpenOutline,
  AuditOutline,
  LockOutline,
  DoubleLeftOutline,
  DoubleRightOutline,
  PlusOutline,
  SaveOutline,
  SettingOutline,
  FlagOutline,
  SearchOutline,
  MenuUnfoldOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  UserSwitchOutline,
  StarOutline,
  SyncOutline,
  ImportOutline,
  FileSearchOutline,
  FileExcelOutline,
  ExportOutline,
  ContainerOutline,
  DatabaseOutline,
  CommentOutline,
  SnippetsOutline,
  FileSyncOutline,
  SwapOutline,
  ReloadOutline,
  MoreOutline,
} from '@ant-design/icons-angular/icons';

export const antIcons: IconDefinition[] = [   //fill
  StarFill,
  StopFill,
  TrademarkCircleFill,
  FlagFill,
  // outline
  LogoutOutline,
  UserOutline,
  EditOutline,
  DownloadOutline,
  FolderOpenOutline,
  AuditOutline,
  LockOutline,
  DoubleLeftOutline,
  DoubleRightOutline,
  PlusOutline,
  SaveOutline,
  SettingOutline,
  FlagOutline,
  SearchOutline,
  MenuUnfoldOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  UserSwitchOutline,
  StarOutline,
  SyncOutline,
  ImportOutline,
  FileSearchOutline,
  FileExcelOutline,
  ExportOutline,
  ContainerOutline,
  DatabaseOutline,
  CommentOutline,
  SnippetsOutline,
  FileSyncOutline,
  SwapOutline,
  ReloadOutline,
  MoreOutline,
  ];

export const ngZorroConfig: NzConfig = {
  message: { nzTop: 16, },
  notification: { nzTop: 16, nzPlacement:'top' },
  table: { nzBordered: true },
  // datePicker:{nzLocale :{en}}
};
